<?xml version="1.0"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<package format="3">
  <name>mission_coordinator</name>
  <version>0.1.0</version>
  <description>Transport-independent factory mission state machine.</description>
  <maintainer email="nixonedwardwinata2004@gmail.com">Nixon Edward Winata</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>factory_interfaces</depend>
  <depend>nav2_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <test_depend>rosgraph_msgs</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
