# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.8)
project(factory_bringup)
find_package(ament_cmake REQUIRED)
install(DIRECTORY config maps launch DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  find_package(launch_testing_ament_cmake REQUIRED)
  ament_add_pytest_test(test_navigation_config test/test_navigation_config.py)
  add_launch_test(test/test_navigation_goal.py TIMEOUT 180)
endif()
ament_package()
