<?xml version="1.0"?>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<package format="3">
  <name>fleet_manager</name>
  <version>0.1.0</version>
  <description>Validated fleet configuration and global coordination.</description>
  <maintainer email="nixonedwardwinata2004@gmail.com">Nixon Edward Winata</maintainer>
  <license>Apache-2.0</license>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>factory_interfaces</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
